### ISSUE TITLE
How to implement Timeline in a Fragment with ViewPager

### ISSUE THREAD

**Issue by ahmetcavdar** [vipulasri/Timeline-View#26]
public class IslemlerFragment extends Fragment {

    private static final String ARG_PARAM1 = "param1";
    private static final String ARG_PARAM2 = "param2";
    // TODO: Rename and change types of parameters
    private String mParam1;
    private String mParam2;

    private RecyclerView mRecyclerView;
    private TimeLineAdapter mTimeLineAdapter;
    private List<TimeLineModel> mDataList = new ArrayList<>();
    private Orientation mOrientation;
    private boolean mWithLinePadding;

    public IslemlerFragment() {
        // Required empty public constructor
    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param param1 Parameter 1.
     * @param param2 Parameter 2.
     * @return A new instance of fragment IslemlerFragment.
     */
    // TODO: Rename and change types and number of parameters
    public static IslemlerFragment newInstance(String param1, String param2) {
        IslemlerFragment fragment = new IslemlerFragment();
        Bundle args = new Bundle();
        args.putString(ARG_PARAM1, param1);
        args.putString(ARG_PARAM2, param2);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            mParam1 = getArguments().getString(ARG_PARAM1);
            mParam2 = getArguments().getString(ARG_PARAM2);

            mDataList.add(new TimeLineModel("Item successfully delivered", "", OrderStatus.INACTIVE));
            mDataList.add(new TimeLineModel("Courier is out to delivery your order", "2017-02-12 08:00", OrderStatus.ACTIVE));
            mDataList.add(new TimeLineModel("Item has reached courier facility at New Delhi", "2017-02-11 21:00", OrderStatus.COMPLETED));
            mDataList.add(new TimeLineModel("Item has been given to the courier", "2017-02-11 18:00", OrderStatus.COMPLETED));
            mDataList.add(new TimeLineModel("Item is packed and will dispatch soon", "2017-02-11 09:30", OrderStatus.COMPLETED));
            mDataList.add(new TimeLineModel("Order is being readied for dispatch", "2017-02-11 08:00", OrderStatus.COMPLETED));
            mDataList.add(new TimeLineModel("Order processing initiated", "2017-02-10 15:00", OrderStatus.COMPLETED));
            mDataList.add(new TimeLineModel("Order confirmed by seller", "2017-02-10 14:30", OrderStatus.COMPLETED));
            mDataList.add(new TimeLineModel("Order placed successfully", "2017-02-10 14:00", OrderStatus.COMPLETED));
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.fragment_islemler, container, false);

        mOrientation = Orientation.VERTICAL;
        mWithLinePadding = true;

        mRecyclerView = (RecyclerView) view.findViewById(R.id.recyclerView);
        LinearLayoutManager llm = new LinearLayoutManager(getActivity());

        mRecyclerView.setLayoutManager(llm);
        mRecyclerView.setHasFixedSize(true);

        mTimeLineAdapter = new TimeLineAdapter(mDataList, mOrientation, mWithLinePadding);

        mRecyclerView.setAdapter(mTimeLineAdapter);
        //Application crash
        return  view;
    }
    }`

**Comment by vipulasri** [comment]
@ahmetcavdar Please show crash log.

**Comment by ahmetcavdar** [comment]
03-13 20:16:26.518 19317-19317/com.makronik.hesaptakibi D/Zygote: CtrlSocket libc.so ctrl_sockets_set_addr pfunc is not exist!
03-13 20:16:26.528 19317-19317/com.makronik.hesaptakibi I/art: Late-enabling -Xcheck:jni
03-13 20:16:26.568 19317-19317/com.makronik.hesaptakibi D/ActivityThread: ActivityThread,attachApplication
03-13 20:16:26.588 19317-19317/com.makronik.hesaptakibi D/HwCust: Create obj success use class android.content.res.HwCustHwResourcesImpl
03-13 20:16:26.728 19317-19317/com.makronik.hesaptakibi W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.makronik.hesaptakibi-1/split_lib_dependencies_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.makronik.hesaptakibi-1@split_lib_dependencies_apk.apk@classes.dex) because non-0 exit status
03-13 20:16:27.058 19317-19317/com.makronik.hesaptakibi W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.makronik.hesaptakibi-1/split_lib_slice_0_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.makronik.hesaptakibi-1@split_lib_slice_0_apk.apk@classes.dex) because non-0 exit status
03-13 20:16:27.148 19317-19317/com.makronik.hesaptakibi W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.makronik.hesaptakibi-1/split_lib_slice_1_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.makronik.hesaptakibi-1@split_lib_slice_1_apk.apk@classes.dex) because non-0 exit status
03-13 20:16:27.218 19317-19317/com.makronik.hesaptakibi W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.makronik.hesaptakibi-1/split_lib_slice_2_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.makronik.hesaptakibi-1@split_lib_slice_2_apk.apk@classes.dex) because non-0 exit status
03-13 20:16:27.298 19317-19317/com.makronik.hesaptakibi W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.makronik.hesaptakibi-1/split_lib_slice_3_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.makronik.hesaptakibi-1@split_lib_slice_3_apk.apk@classes.dex) because non-0 exit status
03-13 20:16:27.388 19317-19317/com.makronik.hesaptakibi W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.makronik.hesaptakibi-1/split_lib_slice_4_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.makronik.hesaptakibi-1@split_lib_slice_4_apk.apk@classes.dex) because non-0 exit status
03-13 20:16:27.458 19317-19317/com.makronik.hesaptakibi W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.makronik.hesaptakibi-1/split_lib_slice_5_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.makronik.hesaptakibi-1@split_lib_slice_5_apk.apk@classes.dex) because non-0 exit status
03-13 20:16:27.528 19317-19317/com.makronik.hesaptakibi W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.makronik.hesaptakibi-1/split_lib_slice_6_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.makronik.hesaptakibi-1@split_lib_slice_6_apk.apk@classes.dex) because non-0 exit status
03-13 20:16:27.628 19317-19317/com.makronik.hesaptakibi W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.makronik.hesaptakibi-1/split_lib_slice_7_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.makronik.hesaptakibi-1@split_lib_slice_7_apk.apk@classes.dex) because non-0 exit status
03-13 20:16:27.688 19317-19317/com.makronik.hesaptakibi W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.makronik.hesaptakibi-1/split_lib_slice_8_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.makronik.hesaptakibi-1@split_lib_slice_8_apk.apk@classes.dex) because non-0 exit status
03-13 20:16:27.738 19317-19317/com.makronik.hesaptakibi W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.makronik.hesaptakibi-1/split_lib_slice_9_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.makronik.hesaptakibi-1@split_lib_slice_9_apk.apk@classes.dex) because non-0 exit status
03-13 20:16:27.738 19317-19317/com.makronik.hesaptakibi W/System: ClassLoader referenced unknown path: /data/app/com.makronik.hesaptakibi-1/lib/arm64
03-13 20:16:27.748 19317-19317/com.makronik.hesaptakibi I/InstantRun: Starting Instant Run Server for com.makronik.hesaptakibi
03-13 20:17:19.578 19317-19317/com.makronik.hesaptakibi V/HwPolicyFactory: : success to get AllImpl object and return....
03-13 20:17:19.588 19317-19317/com.makronik.hesaptakibi V/HwWidgetFactory: : successes to get AllImpl object and return....
03-13 20:17:19.628 19317-19317/com.makronik.hesaptakibi V/ActivityThread: ActivityThread,callActivityOnCreate
03-13 20:17:19.778 19317-19317/com.makronik.hesaptakibi V/ActivityThread: ActivityThread,callActivityOnCreate
03-13 20:17:19.808 19317-19317/com.makronik.hesaptakibi W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
03-13 20:17:20.038 19317-19317/com.makronik.hesaptakibi V/BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
03-13 20:17:20.038 19317-19317/com.makronik.hesaptakibi V/BoostFramework: mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
03-13 20:17:20.038 19317-19317/com.makronik.hesaptakibi V/BoostFramework: mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
03-13 20:17:20.038 19317-19317/com.makronik.hesaptakibi V/BoostFramework: mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
03-13 20:17:20.038 19317-19317/com.makronik.hesaptakibi V/BoostFramework: mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()
03-13 20:17:20.048 19317-19317/com.makronik.hesaptakibi V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@3b200ba
03-13 20:17:20.138 19317-19317/com.makronik.hesaptakibi W/AHBottomNavigation: The items list should have at least 3 items
03-13 20:17:20.168 19317-19317/com.makronik.hesaptakibi I/HwSecImmHelper: mSecurityInputMethodService is null
03-13 20:17:20.168 19317-20862/com.makronik.hesaptakibi D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
03-13 20:17:20.278 19317-19317/com.makronik.hesaptakibi D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.15, mControlPoint1y = 0.7, mControlPoint2x = 0.2, mControlPoint2y = 0.98
03-13 20:17:20.278 19317-19317/com.makronik.hesaptakibi D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
03-13 20:17:20.278 19317-19317/com.makronik.hesaptakibi V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@2d9243f
03-13 20:17:20.278 19317-19317/com.makronik.hesaptakibi D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.15, mControlPoint1y = 0.7, mControlPoint2x = 0.2, mControlPoint2y = 0.98
03-13 20:17:20.278 19317-19317/com.makronik.hesaptakibi D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
03-13 20:17:20.278 19317-19317/com.makronik.hesaptakibi V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@739d10c
03-13 20:17:20.398 19317-19317/com.makronik.hesaptakibi D/AndroidRuntime: Shutting down VM
03-13 20:17:20.398 19317-19317/com.makronik.hesaptakibi E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.makronik.hesaptakibi, PID: 19317
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.vipulasri.timelineview.TimelineView.initLine(int)' on a null object reference
                                                                              at com.makronik.hesaptakibi.TimeLineViewHolder.<init>(TimeLineViewHolder.java:29)
                                                                              at com.makronik.hesaptakibi.TimeLineAdapter.onCreateViewHolder(TimeLineAdapter.java:54)
                                                                              at com.makronik.hesaptakibi.TimeLineAdapter.onCreateViewHolder(TimeLineAdapter.java:23)
                                                                              at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6321)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5509)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
                                                                              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                              at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
                                                                              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                              at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3537)
                                                                              at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2979)
                                                                              at android.view.View.measure(View.java:18930)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5976)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                              at android.view.View.measure(View.java:18930)
                                                                              at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
                                                                              at android.view.View.measure(View.java:18930)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5976)
                                                                              at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
                                                                              at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:786)
                                                                              at android.view.View.measure(View.java:18930)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5976)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                              at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                              at android.view.View.measure(View.java:18930)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5976)
                                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1486)
                                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:765)
                                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:647)
                                                                              at android.view.View.measure(View.java:18930)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5976)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                              at android.view.View.measure(View.java:18930)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5976)
                                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1486)
                                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:765)
                                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:647)
                                                                              at android.view.View.measure(View.java:18930)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5976)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                              at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2705)
                                                                              at android.view.View.measure(View.java:18930)
                                                                              at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2154)
                                                                              at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1248)
                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1484)
                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6238)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:884)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:696)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                          	at android.view.Choreographer$Frame
03-13 20:17:20.728 19317-19317/com.makronik.hesaptakibi I/Process: Sending signal. PID: 19317 SIG: 9

**Comment by vipulasri** [comment]
@ahmetcavdar according to log, the error lies in your `TimelineViewHolder` you might have not properly implemented `Timeline` using `findViewById`. Please check the initialization of views.

**Comment by ahmetcavdar** [comment]
public class TimeLineViewHolder extends RecyclerView.ViewHolder {

    @BindView(R.id.text_timeline_date)
    TextView mDate;
    @BindView(R.id.text_timeline_title)
    TextView mMessage;
    @BindView(R.id.time_marker)
    TimelineView mTimelineView;

    public TimeLineViewHolder(View itemView, int viewType) {
        super(itemView);

        ButterKnife.bind(this, itemView);
        mTimelineView.initLine(viewType);
    }
    }
'       public TimeLineViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        mContext = parent.getContext();
        mLayoutInflater = LayoutInflater.from(mContext);
        View view;

        view = mLayoutInflater.inflate(R.layout.timeline_item, parent, false);

        return new TimeLineViewHolder(view, viewType);
    }
`

**Comment by vipulasri** [comment]
Can you please upload the project, so that I can take a look?

**Comment by ahmetcavdar** [comment]
I found the problem

    public class TimeLineViewHolder extends RecyclerView.ViewHolder {

    public TextView mDate;
    public TextView mMessage;
    public  TimelineView mTimelineView;

    public TimeLineViewHolder(View itemView, int viewType) {
        super(itemView);

        mDate = (TextView) itemView.findViewById(R.id.text_timeline_date);
        mMessage = (TextView) itemView.findViewById(R.id.text_timeline_title);
        mTimelineView = (TimelineView) itemView.findViewById(R.id.time_marker);
        
        mTimelineView.initLine(viewType);
    }
    }
`
