### ISSUE TITLE
In api<21 getting error: Error inflating class com.github.vipulasri.timelineview.TimelineView

### ISSUE THREAD

**Issue by kvipul** [vipulasri/Timeline-View#50]
Getting an app crash while testing library in api 16

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    android.view.InflateException: Binary XML file line #0: Error inflating class com.github.vipulasri.timelineview.TimelineView
                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                        at com.adapter.MyAdapter.onCreateViewHolder(MyAdapter.java:48)
                                                                        at com.adapter.MyAdapter.onCreateViewHolder(MyAdapter.java:35)
                                                                        at jp.wasabeef.recyclerview.adapters.AnimationAdapter.onCreateViewHolder(AnimationAdapter.java:40)
                                                                        at jp.wasabeef.recyclerview.adapters.AnimationAdapter.onCreateViewHolder(AnimationAdapter.java:40)
                                                                        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6519)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5706)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
                                                                        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                        at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3135)
                                                                        at android.view.View.measure(View.java:15172)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
                                                                        at android.view.View.measure(View.java:15172)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
                                                                        at android.view.View.measure(View.java:15172)
                                                                        at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1449)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                        at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:515)
                                                                        at android.view.View.measure(View.java:15172)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                        at android.view.View.measure(View.java:15172)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
                                                                        at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:400)
                                                                        at android.view.View.measure(View.java:15172)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                        at android.view.View.measure(View.java:15172)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
                                                                        at android.view.View.measure(View.java:15172)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2148)
                                                                    	at android.view.Vi`

**Comment by kvipul** [comment]
Solution:
(This is a workaround until admin doesn't fix the issue in library) 
I was using vector drawables for marker in xml files. You can't simply use vector drawables for api<21. Here is a solution that I found helpful for using vector drawables for api<21 [Stackoverflow link](https://stackoverflow.com/a/40523623/5745574)

So after using above solution try avoiding setting app:marker attributes in the xml file and set it in the java class.

**Comment by vipulasri** [comment]
You cannot set vector drawable from XML and I won't even support in near future. 
You can also see the sample app, which includes code to dynamically set vector drawable to marker(works on pre-lollipop) as well.

**Comment by kvipul** [comment]
In that case I suggest you to mention this in readme file so that in future people are aware of this before using the library.

Thanks 😄
