### ISSUE TITLE
App crashed on pre lollipop device

### ISSUE THREAD

**Issue by SachinTanpure** [vipulasri/Timeline-View#51]
Device details
Samsung galaxy S3 SGH-T999, Android 4.3
Lava irisX8, Android 4.4

compileSdkVersion 25
buildToolsVersion "25.0.2"
i am using 'com.github.vipulasri:timelineview:1.0.6'

System log is as follows
FATAL EXCEPTION: main
                      java.lang.IllegalArgumentException: radius must be > 0
                          at android.graphics.RadialGradient.<init>(RadialGradient.java:53)
                          at android.support.v7.widget.RoundRectDrawableWithShadow.buildShadowCorners(RoundRectDrawableWithShadow.java:323)
                          at android.support.v7.widget.RoundRectDrawableWithShadow.buildComponents(RoundRectDrawableWithShadow.java:345)
                          at android.support.v7.widget.RoundRectDrawableWithShadow.draw(RoundRectDrawableWithShadow.java:247)
                          at android.view.View.draw(View.java:14721)
                          at android.widget.FrameLayout.draw(FrameLayout.java:534)
                          at android.view.View.getDisplayList(View.java:13602)
                          at android.view.View.getDisplayList(View.java:13649)
                          at android.view.View.draw(View.java:14444)
                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                          at android.view.View.getDisplayList(View.java:13594)
                          at android.view.View.getDisplayList(View.java:13649)
                          at android.view.View.draw(View.java:14444)
                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                          at android.view.View.getDisplayList(View.java:13594)
                          at android.view.View.getDisplayList(View.java:13649)
                          at android.view.View.draw(View.java:14444)
                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                          at android.view.View.draw(View.java:14753)
                          at android.widget.FrameLayout.draw(FrameLayout.java:534)
                          at android.view.View.getDisplayList(View.java:13602)
                          at android.view.View.getDisplayList(View.java:13649)
                          at android.view.View.draw(View.java:14444)
                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                          at android.view.View.getDisplayList(View.java:13594)
                          at android.view.View.getDisplayList(View.java:13649)
                          at android.view.View.draw(View.java:14444)
                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                          at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4477)
                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                          at android.view.View.draw(View.java:14753)
                          at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3869)
                          at android.view.View.getDisplayList(View.java:13602)
                          at android.view.View.getDisplayList(View.java:13649)
                          at android.view.View.draw(View.java:14444)
                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                          at android.view.View.getDisplayList(View.java:13594)
                          at android.view.View.getDisplayList(View.java:13649)
                          at android.view.View.draw(View.java:14444)
                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                          at android.view.View.getDisplayList(View.java:13594)
                          at android.view.View.getDisplayList(View.java:13649)
                          at android.view.View.draw(View.java:14444)
                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                          at android.view.View.getDisplayList(View.java:13594)
                          at android.view.View.getDisplayList(View.java:13649)
                          at android.view.View.draw(View.java:14444)
                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                          at android.view.View.getDisplayList(View.java:13594)
                          at android.view.View.getDisplayList(View.java:13649)
                          at android.view.View.draw(View.java:14444)
                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                          at android.view.View.getDisplayList(View.java:13594)
                          at android.view.View.getDisplayList(View.java:13649)
                          at android.view.View.draw(View.java:14444)
                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3090)
                          at android.view.View.draw(View.java:14753)
                          at android.view.View.getDisplayList(View.java:13602)
                          at android.view.View.getDisplayList(View.java:13649)
                      	at android.view.

**Comment by vipulasri** [comment]
@SachinTanpure I will look into. Thanks for mentioning.

**Comment by vipulasri** [comment]
@SachinTanpure Cna you show me your code?

**Comment by SachinTanpure** [comment]
@vipulasri Sorry to bother you, issue was from my side.
